### ISSUE TITLE
Search not work.

### ISSUE THREAD

**Issue by fhyrox** [nuxt-themes/docus#1011]
The search button does not work and does not send an error to the console. Also, there is no theme change button in the template I use. I downloaded the template via NPX.

Google Translate

**Comment by fssou** [comment]
@fhyrox look here https://github.com/nuxt-themes/docus/issues/1007#issuecomment-1826353478 fdp

**Comment by fhyrox** [comment]
> @fhyrox look here [#1007 (comment)](https://github.com/nuxt-themes/docus/issues/1007#issuecomment-1826353478) fdp

thanks, worked but, color mode dont working

**Comment by fhyrox** [comment]
okay worked. thanks.
