### ISSUE TITLE
feat: link between pages

### ISSUE THREAD

**Issue by Atinux** [nuxt-themes/docus#241]
At the moment we need to specify the whole link: `[About](/about)`

It could be nice to be able to link to a page by using some special syntax like RoamResearch or Obsidian.md: `[[about]]`

The content between the brackets would be the slug of the page, transforming it to `[About](/about)`. 

One issue of having this would be when you want to use a custom title for the link :thinking:

**Comment by Tahul** [comment]
Curious of exploring using a Volar plugin for global type generation support from @nuxt/content

**Comment by Tahul** [comment]
Should we move this to https://github.com/nuxtlabs/vscode-mdc ?

**Comment by Atinux** [comment]
I think this is out of scope of Docus right now
