### ISSUE TITLE
Use @vueuse/schema-org

### ISSUE THREAD

**Issue by Atinux** [nuxt-themes/docus#554]
Let's make the best SEO from scratch using https://vue-schema-org.netlify.app :blush: 

We need to forward the main document metadata to `defineWebPage` as well:
https://vue-schema-org.netlify.app/guide/setup/nuxt.html#_4-optional-webpage-configuration

**Comment by Tahul** [comment]
@Atinux ; WDYT of moving this in Elements, creating a components/seo directory?
