### ISSUE TITLE
Review: Navigation

### ISSUE THREAD

**Issue by Tahul** [nuxt-themes/docus#602]
Navigation deserves an in-depth review as well.

The current setup we have has been the result of lots of iterations and cleanups and I think it cover a lot of possible navigation setups greatly.

Yet, I think we should add few more features:
- Add a slot to support a sub-navbar like in Nuxt.com website (can be done from `docs` layouts) (#601)
- Improve support for big contents (10+ directories, 10+ pages, in-depth tests with a lot of content..)
- Add support for automatic home redirect (#573)
- Improve error pages

**Comment by Tahul** [comment]
I think this is still relevant;

WDYT @Atinux @bdrtsky ?

**Comment by Atinux** [comment]
Yes, but worth splitting in smaller tasks

**Comment by Tahul** [comment]
![image.png](https://volta.s3.fr-par.scw.cloud/image_459571ccea.png)

@bdrtsky ; from our Slack discussion with @Atinux

Need to fix that icon problem

**Comment by Tahul** [comment]
?

**Comment by Tahul** [comment]
?

**Comment by Tahul** [comment]
test??
