### ISSUE TITLE
Fix overflow on aside link

### ISSUE THREAD

**Issue by Atinux** [nuxt-themes/docus#627]
We should use ellipsis text-overflow:
![CleanShot 2022-09-07 at 20.02.31@2x.png](https://volta.s3.fr-par.scw.cloud/Clean_Shot_2022_09_07_at_20_02_31_2x_63ced090f8.png)

**Comment by bdrtsky** [comment]
Maybe remove truncation and allow multiline instead? Truncation is ok for TOC (as you have same text in Headings duplicated), but for aside menu I prefer to see whole text

**Comment by Atinux** [comment]
Agree for multiline!

**Comment by bdrtsky** [comment]
Should be fixed already.
