### ISSUE TITLE
Inconsistent starter docs

### ISSUE THREAD

**Issue by nanthony007** [nuxt-themes/docus#672]
The website's getting started section says to run `npx nuxi init docs -t themes/docus` which fails, while this repo says to run `npx nuxi init docs -t nuxt-themes/docus` which succeeds. 

I'd be happy to fix this typo (in `.docs/content/getting-started.md`) if that is acceptable.

**Comment by danielroe** [comment]
This probably indicates you have an outdated nuxi version cached by npm. Try `npx nuxi@latest init docs -t themes/docus`.
