### ISSUE TITLE
`tocLink` anchor link generate extra hyphen at the end

### ISSUE THREAD

**Issue by twodft** [nuxt-themes/docus#678]
Check those anchor links
```
https://docus.dev/api/components#alert-
https://docus.dev/api/components#badge-
```

there is an extra `-` at the end.

**Comment by Atinux** [comment]
I think this is related to Nuxt Content, I guess it's about the `/` or ` ` transformed as `-`.

Maybe we can improve this @farnabaz ?

**Comment by Tahul** [comment]
https://github.com/nuxt/content/blob/ef92b203165f3034543e2e1ee9925015b060ce96/src/runtime/markdown-parser/toc.ts#L55

I guess it comes from this line, maybe we could sanitize the output?
