### ISSUE TITLE
Using TailwindCSS

### ISSUE THREAD

**Issue by zoey-kaiser** [nuxt-themes/docus#689]
I wanted to write some custom components with the help of TailwindCSS. 

I attempted to install `@nuxtjs/tailwindcss` as a dev dependency, added the module to the `modules` section of my nuxt-config and had the tailwindcss config check for classes in the `components` folder.

However this sadly did not work. Is there another way for me to integrate TailwindCSS? I prefer working with it over vanilla CSS or pinceau.

Thank you in advance!

**Comment by Atinux** [comment]
It should work, could you share your repository or reproduction so we can have a look please?

**Comment by zoey-kaiser** [comment]
> It should work, could you share your repository or reproduction so we can have a look please?

My bad! I was testing to see if TailwindCSS would work by adding a simple `text-blue` to a text element. I just tried it with another class and it worked!
