### ISSUE TITLE
is there something wrong with Built-In Components?

### ISSUE THREAD

**Issue by itsmnthn** [nuxt-themes/docus#691]
I cannot see the preview of components in the Docus docs. I'm using the Docus theme for the docs and after updating from `v0.3.2` to `v1.0.0` I find the built-in components like cards and tailwind are not working. I saw `v1.0.0` is a breaking change but could not find a better document to make things work again.

![Screenshot 2022-11-26 at 11 35 29 AM](https://user-images.githubusercontent.com/25129674/204074836-63225f1e-9509-4f28-9b04-9e3db75ff345.png)

**Comment by Atinux** [comment]
cc @tahul

**Comment by Tahul** [comment]
Hey @itsmnthn ;

Thanks for raising up the issue, I didn't noticed on latest deployments the page was broken.

It should be resolved by latest commits.

Concerning Tailwind, we dropped it internally in our themes, but as your Docus project is still a regular Nuxt project, you can add Tailwind yourself and use it as it pleases you, it's fully compatible with our themes.
