### ISSUE TITLE
style: <h> style are affected

### ISSUE THREAD

**Issue by gumingWu** [nuxt-themes/docus#693]
Using "@nuxt-themes/docus": "^1.0.1", I thought some style are affected, like h1 h2 h3 h4, maybe more

before using docus
![image](https://user-images.githubusercontent.com/24989299/204144423-686d74a3-fe0b-4b59-ae8c-b62303a350c9.png)

after using
![image](https://user-images.githubusercontent.com/24989299/204144405-87bedbef-2493-49f0-8f4b-a7d655868300.png)

**Comment by Atinux** [comment]
Could you share a repository or reproduction?

**Comment by gumingWu** [comment]
> Could you share a repository or reproduction?

I push my code to the [repository](https://github.com/gumingWu/dailyhand), can you watch it?

**Comment by Tahul** [comment]
Hey @gumingWu ;

I don't exactly understand the issue.

I've checked at your repository, and if you use Docus, we'll be loading a CSS reset, that removes styling from native tags.

Basically, same reset as some other CSS frameworks.

If you want to get same styling as `h1/2/3/4/5` from Prose, you can use `<ProseH1/2/3/4/5>` component from your templates.

I'll close this issue as it's not one, but feel free to re-open if this is unclear.

**Comment by xarthurx** [comment]
> 



> Hey @gumingWu ;
> 
> I've checked at your repository, and if you use Docus, we'll be loading a CSS reset, that removes styling from native tags.
> 
> Basically, same reset as some other CSS frameworks.
> 
> If you want to get same styling as `h1/2/3/4/5` from Prose, you can use `<ProseH1/2/3/4/5>` component from your templates.
> 
> I'll close this issue as it's not one, but feel free to re-open if this is unclear.

I tried to use a different reset from `unocss` by `import "@unocss/reset/normalize.css"`, but Docus's one is overriding mine.
Is it possible to allow css override globally?
