### ISSUE TITLE
Use of docus in turborepo

### ISSUE THREAD

**Issue by jelmergerritsma** [nuxt-themes/docus#696]
I use a mono repo with Turborepo. And in the apps folder i installed docus under a docs folder. When i try to run the dev script i get an error that the theme could not be resolved. 

This only appears to happen in a monorepo. When installed standalone in a different folder works fine. It seems the reference path to "#pinceau/theme/flat" only works for those situations.
 
![image](https://user-images.githubusercontent.com/1921314/204297782-a04a500d-52e2-42c0-9270-3b73ee825ce5.png)

**Comment by HelloAlexPan** [comment]
+ 1

**Comment by jelmergerritsma** [comment]
> It looks like the Pinceau library doesn't behave well with dependency hoisting.
> 
> If you're using Yarn workspaces to manage your dependencies, I managed to fix this by adding the following to my `docs/package.json` file:
> 
> ```ts
> "workspaces": {
>   "nohoist": [
>     "@nuxt-themes/docus",
>     "@nuxt-themes/docus/**"
>   ]
> }
> ```
> 
> Edit: On a side note, I've had problems running Nuxt 3 projects in general with the `@nuxt/content` module in a monorepo configuration. If you're using Nuxt Content for any of your other packages, I'd recommend also including `@nuxt/content` and `@nuxt/content/**` in that package's `workspaces.nohoist` array.

I didn't think about dependancy hoisting it did work thanks!
Still i think it would be better if the package didn't need it.

**Comment by Joepocalyptic** [comment]
> I didn't think about dependancy hoisting it did work thanks!
> Still i think it would be better if the package didn't need it.

I agree; monorepo support is pretty much a necessity for a docs framework.

Since the issue appears to be with Pinceau, maybe this would be better suited as a new issue at [Tahul/pinceau](https://github.com/Tahul/pinceau)? @Tahul

**Comment by Tahul** [comment]
Hello here :)

Thank you for reporting this.

I will happily fix this issue in both @nuxt/content and Pinceau.

Does anyone of you has examples of similar issues on other libraries/modules?

**Comment by Tahul** [comment]
Found these lines in Nuxt package:
https://github.com/nuxt/framework/blob/a50855babe8860de508d32fbe7f259831b852b10/packages/nuxt/package.json#L23-L27

I will try this in order to fix issues on Pinceau.

**Comment by Tahul** [comment]
Hello @jelmergerritsma ; could you please try `^1.1.1` and tell me if this `#pinceau` import error still occur in your context?

I pushed a fix upstream that should avoid this kind of error message?

**Comment by jelmergerritsma** [comment]
> 

Heey, I set `@nuxt-themes/docus": "^1.1.1` and installed it. The error is still there and there are some new ones.
<img width="936" alt="image" src="https://user-images.githubusercontent.com/1921314/205431926-391fdc09-dea6-49dc-8a89-1450cf78ff4a.png">
This error also occured for `lightblue`

**Comment by Joepocalyptic** [comment]
> Hello @jelmergerritsma ; could you please try `^1.1.1` and tell me if this `#pinceau` import error still occur in your context?
> 
> I pushed a fix upstream that should avoid this kind of error message?

I'm having the same issues as @jelmergerritsma in my own project with version 1.1.1.

![image](https://user-images.githubusercontent.com/42530725/205457015-dbe7966c-34a8-4700-ac1d-a6749b44331f.png)
![image](https://user-images.githubusercontent.com/42530725/205457033-e8a6398d-33a4-4cde-bec7-bb545165fd04.png)

**Comment by Joepocalyptic** [comment]
Upon further investigation, it seems that the new errors within `tokens.config.ts` occur even when dependency hoisting is disabled. It seems that version 1.1.1 isn't working under any circumstances with Yarn workspaces now.

**Comment by Tahul** [comment]
Hello @Joepocalyptic ; could you provide a reproduction please?

@jelmergerritsma ; are you sure you also upgraded your lockfile?

Could you both check the Pinceau version in your lockfile is ^0.8.3?

Thanks 🙏

**Comment by Tahul** [comment]
@Joepocalyptic ; is this issue still relevant for latest versions of Docus?

**Comment by jelmergerritsma** [comment]
@Tahul Sorry for the late replies havent been coding due to family circumstances. I updated the docus version to 1.1.3 (latest) in the package.json. I don't see the resolve errors of the pinceau them anymore but the theme error stil exist. This is without dependacny hoisting.

**Comment by Atinux** [comment]
Happy to upgrade again and tell us if you have time?

**Comment by jelmergerritsma** [comment]
@Atinux After the update everything worked fine. No more issues and errors. Thanks alot!
