### ISSUE TITLE
[Page Layout] `constrained-class` does not work

### ISSUE THREAD

**Issue by farnabaz** [nuxt-themes/docus#702]
`constrained-class` passes to `AppContainer` but the component does not use it in the template.

Layout:
https://github.com/nuxt-themes/docus/blob/1237388f0038efe11b85271578c2358638199d5c/layouts/page.vue#L7

Component:
https://github.com/nuxt-themes/docus/blob/dev/components/app/AppContainer.vue

**Comment by farnabaz** [comment]
@bdrtsky Indeed `maxWidth` solved the issue.

**Comment by farnabaz** [comment]
How should I pass this value for specific page? in front-matter?

```md
---
container:
  maxWidth: ??
---
```

And what are the accepted values?

**Comment by bdrtsky** [comment]
Interesting request, I am afraid modifying tokens from front-matter is not possible. And I am not sure you suppose to do that in general. Why would you change app container width per route? It feels weird when your layout jumps in width when you navigate. What you think @Tahul 

As for accepted properties, it's all values CSS supports: 1028px, 50rem etc.
