### ISSUE TITLE
Feature Request: Ability to override theme components

### ISSUE THREAD

**Issue by themodernpk** [nuxt-themes/docus#706]
Hi Again,

It will be good to have the ability to override theme components like `header`, `footer` or other `assets`.

Imagine a command:
```
npx nuxi publish themes/docus

or

npx nuxi publishable themes/docus

```

which publishes all the assets like components, images, CSS, etc in the respective folder at the root of the project.

Now, developers will have the ability to edit those assets and `nuxt` should give priority to the assets at the root directory.

Again, this is very similar, to how laravel handles overriding the assets from various packages.

**Comment by Atinux** [comment]
Actually you should be able to overwrite any component from docus by creating the component with the same name in your `components/` directory (we need to document this).

Example: `~/components/AppHeader.vue` to overwrite https://github.com/nuxt-themes/docus/blob/dev/components/app/AppHeader.vue

**Comment by Tahul** [comment]
I really like the idea of having a `nuxi publish` command, like Laravel, that finds a component by its name and copy it to your repository in same spot so you can start overwriting it.

**Comment by Tahul** [comment]
Hey, that question seem to be answered by two previous comments.

I'm closing this now, but feel free to re-open if you want to push this further! :)
