### ISSUE TITLE
TabsHeader: When the number of tabs is too large, horizontal scrolling is not enabled

### ISSUE THREAD

**Issue by jerrywu001** [nuxt-themes/docus#707]
`@nuxt-themes/element`/components/globals/TabsHeader

When the number of tabs is too large

***1. horizontal scrolling is not enabled***

***2. And The text wrapped***

Effect

![image](https://user-images.githubusercontent.com/12525415/205251320-8792e688-a397-472e-8b6a-bfd59f6373fe.png)

---
I simply modified the code:

```diff
// @nuxt-themes/element/components/globals/TabsHeader

<style scoped lang="ts">
css({
  ".tabs-header": {
    ...,
    '.tabs': {
      ...,
+      overflowX: 'auto',
      button: {
+        flex: 'none',
        py: '{space.2-5}',
        px: '{space.4}',
```

And It works
![image](https://user-images.githubusercontent.com/12525415/205251768-7c9cfc02-4d0b-46e6-82c5-5cb22c287546.png)

**Comment by Atinux** [comment]
Happy to open a PR @jerrywu001 ?

Thanks for the report 🙏

**Comment by bdrtsky** [comment]
I will update Elements, thanks @jerrywu001
