### ISSUE TITLE
Legacy integrations import

### ISSUE THREAD

**Issue by Tahul** [nuxt-themes/docus#712]
Old GitHub integration usually on `/releases` or `/changelog` page is currently broken.

The nuxtlabs/github-module still works, and still is compatible with Docus.

We just need to take a decision about this module and how we should orchestrate this integration.

I have two questions about this:
- If we provide integrations that can be used from multiple themes, should we do it from Elements? (cc @Atinux)
- What is the best way to detect the presence of a module in Nuxt 3? (cc @danielroe)
	- at runtime?
	- inside another module?

**Comment by Atinux** [comment]
I believe best would be to integrate GitHub with Elements directly.
