### ISSUE TITLE
Code highlighting inside `callouts` is off

### ISSUE THREAD

**Issue by BracketJohn** [nuxt-themes/docus#720]
When adding a code block into a `callout` element, it looks like this:
![image](https://user-images.githubusercontent.com/25911230/206855597-caeaf301-ced2-4516-a4bb-c173a7642d9f.png)

source: https://sidebase.io/nuxt-prisma/getting-started/quick-start

**Comment by bdrtsky** [comment]
https://github.com/nuxt-themes/elements/pull/169
