### ISSUE TITLE
Add space in the footer for imprint

### ISSUE THREAD

**Issue by zoey-kaiser** [nuxt-themes/docus#726]
Hello! 

We are currently hosting our page in the EU, where it is required by law to have an imprint on your website. Sadly this link cannot be only an icon and must have the work "Imprint" available to read. 

I attempted to add a extra link the footer, however the word imprint would just be cut off, as the space was made for icons.
I ended up having to replace the "Docus" branding text to have a link to our imprint. 

Would it be possible to allow developers to add text based links into the footer or add a extra section in the footer for "legal stuff"?

Thanks!

**Comment by Atinux** [comment]
I think we can have a way to add links in the center of the footer, would that work?

**Comment by zoey-kaiser** [comment]
> I think we can have a way to add links in the center of the footer, would that work?

Yes, it would! Do you want me to open a PR and take a crack at it?

**Comment by Atinux** [comment]
First we can discuss about what would be the usage in the `appConfig` from your POV?

**Comment by zoey-kaiser** [comment]
> First we can discuss about what would be the usage in the `appConfig` from your POV?

Sure! My proposal would be to add it to the `footer` key in the appConfig. I would expect it to match the types of the iconLinks (icon, href, label). The key for these links would not be called `iconLinks` but `centerLinks` or `textLinks`, depending on what you prefer or think works best. 

I could then get these values in the footer and display a max of 3? in the center with the icon being optional displayed on the left side of the text.

Next steps would be to make sure the footer still works on mobile devices and all viewports!

**Comment by bdrtsky** [comment]
I would just add `textLinks` without option to have it with icon (hence the name).
