### ISSUE TITLE
Static site generation - broken?

### ISSUE THREAD

**Issue by kirtan403** [nuxt-themes/docus#728]
When using docus to generate static site, the site generates fine and the content navigation works fine. But on refreshing on a route (or visiting some URL directly), shows 404 page.

![image](https://user-images.githubusercontent.com/7900938/207855427-85509337-1155-4ddd-be5b-4c75d63d0e4a.png)

Tested on the `npm run preview` and `Cloudflare Pages`. Both are showing this error.

**Comment by kirtan403** [comment]
Seems to be the deployment issue. Closing.

**Comment by esoubiran-aneo** [comment]
Have the same issue here.

What did you do to have a working deployment ?

**Comment by kirtan403** [comment]
It was a component issue. Actually, the component was using `useAsyncData` function which was throwing an error when `npm run generate` on ci/cd pipeline. So the exact route was not getting generated
