### ISSUE TITLE
Size tap targets appropriately

### ISSUE THREAD

**Issue by harlan-zw** [nuxt-themes/docus#731]
## Issue

![image](https://user-images.githubusercontent.com/5326365/208226621-7f5a6960-f6cc-45bd-bc4b-e578c7add6f8.png)

## Reproduction

Run lighthouse on docus.dev.

Just need to make their paddings a bit bigger and maybe the icon size up a tiny bit

**Comment by Atinux** [comment]
For mobile I guess it's fine, I don't see that very bad honestly

**Comment by harlan-zw** [comment]
Ye only needed for mobile, it's something Google penalises for so probably worth fixing
