### ISSUE TITLE
sidebar will be generated incorrectly

### ISSUE THREAD

**Issue by DrAugus** [nuxt-themes/docus#732]
If my file is a non-English name, the sidebar will be generated incorrectly.

### tree

```
├── _dir.yml
├── 0.index.md
├── 庄子·秋水.md
├── 猫.md
├── 聪明人和傻子和奴才.md
├── 逍遥游·北冥有鱼.md
└── 道德经.md
```

### only this file is displayed normally

the content of `0.index.md` is 
```md
# nothing
```

![1671279054955](https://user-images.githubusercontent.com/34206897/208241213-e05e99d9-3c7a-451e-8b8b-edfaa0c028f9.png)
![1671279054966](https://user-images.githubusercontent.com/34206897/208241218-1a7c9619-7b2b-44b2-85a0-b383fee6e35a.png)

**Comment by Atinux** [comment]
Could you please create a reproduction on Stackblitz please?

**Comment by razbakov** [comment]
I have the same problem. Sidebar navigation is not updated.

<img width="605" alt="Screen Shot 2023-01-12 at 11 23 46 AM" src="https://user-images.githubusercontent.com/298778/212041860-94303eb6-fd53-43fe-bbf9-4aeeabf8a6ed.png">

<img width="569" alt="Screen Shot 2023-01-12 at 11 24 22 AM" src="https://user-images.githubusercontent.com/298778/212041993-89514fc1-4416-4e2b-8983-412d47c19bfe.png">

**Comment by farnabaz** [comment]
This happens because we use slugify for generating content's path and sadly it does not support non-English characters.
So the generated path for these contents are same. (`/articles/part1`). You can define custom `_path` for your contents in front-matters to handle this
```
---
_path: /articles/part1/my-awesome-content
---

Markdown
```

**Comment by razbakov** [comment]
@farnabaz in my case it is English, and it is not working

**Comment by farnabaz** [comment]
@razbakov Could you provide a simple reproduction?

**Comment by razbakov** [comment]
@farnabaz solved! I was renaming files `1.file-1.md` to `10.file-1.md`. I removed `.nuxt` folder and ran `yarn dev` again and it solved the issue. Thanks!
