### ISSUE TITLE
Custom Footer Icons?

### ISSUE THREAD

**Issue by OfficialCRUGG** [nuxt-themes/docus#734]
Hey there,

I couldn't find any documentation on how one creates custom footer icons (`docus.footer.iconLinks`)

How does one do this? I already tried creating a component in a `components/` directory and setting `icon` to the name of that, but that just puts the component name in the footer.

The docs (https://docus.dev/introduction/configuration) use a `component` property instead of `icon` on their full example, but I can't seem to use this on the newest version of Docus. (Unrelated, but that example also uses docus.com on `docus.footer.credits.href` like many other places, but that domain now redirects to nuxt.studio; no clue if this is on purpose)

**Comment by Atinux** [comment]
Hi @OfficialCRUGG 

The link is fixed now thank you.

For the custom Icon, you need to add it into `component/content` or `components/global` so [nuxt-icon](https://github.com/nuxt-modules/icon#usage-) can use it.
