### ISSUE TITLE
bug: pinceau outputDir use .nuxt dir

### ISSUE THREAD

**Issue by danielgdev** [nuxt-themes/docus#747]
Hello 👋,

Build and deploy using the firebase preset.

![Screenshot 2022-12-28 at 19 24 21](https://user-images.githubusercontent.com/59129958/209891630-977d11eb-ea23-43cc-a8e8-15096529894f.png)

I get this error in firebase functions.

![Screenshot 2022-12-28 at 19 17 02](https://user-images.githubusercontent.com/59129958/209891811-e8b7efc5-d663-4243-a554-b23acf20d11d.png)

In `.output/server/chunks/nitro/firebase.mjs`, `pinceau.outputDir` use the .nuxt directory

![Screenshot 2022-12-28 at 19 19 02](https://user-images.githubusercontent.com/59129958/209891992-2b1a0207-e8e0-4311-864e-1b46fdfa1081.png)

I'm using the [docus starter template](https://github.com/nuxt-themes/docus-starter), I was just testing the deployment with Firebase. I hope you can help me 🙏

**Comment by Tahul** [comment]
Hello @danielgdev ; I'll try to make a deployment myself on Firebase Functions!

Thanks for the report, I'm keeping you posted here.

**Comment by Tahul** [comment]
I successfully made a build with `NITRO_PRESET=firebase` locally by following this guide:
https://nitro.unjs.io/deploy/providers/firebase

Could you try it?

Also, could you share your package.json/lockfile content? That would help me understanding your context.

**Comment by danielgdev** [comment]
Thank you @Tahul 🙌

I tried to follow the guide and during the deployment, I have no problems 🚀
My problem is when I call the Firebase Function 😵‍💫

I'm using pnpm, this is my `.pnpmrc` file

```txt
shamefully-hoist=true
strict-peer-dependencies=false
store-dir=.pnpm-store
```


and this is my [pnpm-lock.yaml](https://gist.github.com/danielgdev/61032d32dc4d7d3a4498baffa95a0e28#file-pnpm-lock-yaml)

**Comment by Tahul** [comment]
Hello @danielgdev ; sorry for the late answer, and happy new year! :)

I will be able to debug this Firebase env thing really soon, could you maybe give me better indications in what exact product/deployment approach from Firebase do you use to get that result?

Also, I'm currently releasing the newest version of Docus that includes `pinceau@^0.10.x` which should maybe have effect on this issue (`.css` and theme handling changed in that update).

Could you try it once release?

Will ping you here once done.

**Comment by Tahul** [comment]
Hey, I think this has been fixed by latest versions of Pinceau that no longer make use of `.nuxt/` outputs for the build phase!

I'm closing this but feel free to re-open if this is not the case for you, I would happily help you fixing it.
