### ISSUE TITLE
docus.dev website is not fully rendered

### ISSUE THREAD

**Issue by mathieunicolas** [nuxt-themes/docus#753]
Hello there,

I don't know where to put this, so I just want to inform you the website https://docus.dev looks not fully rendered : there's only one page in each section.

![image](https://user-images.githubusercontent.com/65437872/211655538-d61810db-86c8-4371-a1e7-a199e4c5ddb2.png)
![image](https://user-images.githubusercontent.com/65437872/211655581-5548f9dd-6791-4f83-948b-3a00ee8853ed.png)

**Comment by Tahul** [comment]
Hey @mathieunicolas ; thanks a lot for the report.

It has just been fixed in latest commit, this was due to internal testing for Nuxt Studio on Docus.dev website. 😅
