### ISSUE TITLE
the docs site is completely broken

### ISSUE THREAD

**Issue by productdevbook** [nuxt-themes/docus#754]
website: https://opensource.huntersofbook.com/
github: https://github.com/huntersofbook/huntersofbook/tree/main/docs

localhost dont problem but vercel with deploy this problem

v.1.4.4

![image](https://user-images.githubusercontent.com/38668796/211726721-b32976aa-e68e-4865-9ffc-59391a2852f7.png)

**Comment by productdevbook** [comment]
this is problem vercel, but custom server push working

**Comment by DrAugus** [comment]
same problem in v1.4.5

**Comment by maximepvrt** [comment]
same with vercel and netlify

**Comment by maximepvrt** [comment]
fixed with [v1.4.6](https://github.com/nuxt-themes/docus/releases/tag/v1.4.6)

**Comment by DrAugus** [comment]
> fixed with [v1.4.6](https://github.com/nuxt-themes/docus/releases/tag/v1.4.6)

It doesn't seem to be fixed. Maybe a discussion group should be set up... The recent release does not seem to have been tested

**Comment by Tahul** [comment]
Hello @productdevbook ; could you confirm the latest version fixed your issues?

Thanks a lot! 🙏

**Comment by productdevbook** [comment]
@Tahul no fixed

https://huntersofbook-site-iem4gnk90-productdevbook.vercel.app/

**Comment by productdevbook** [comment]
@Tahul new vercel open and re deploy fixed. 

How to vercel cache delete website ?
