### ISSUE TITLE
Is there a way to opt-out for `__studio` generation?

### ISSUE THREAD

**Issue by Barbapapazes** [nuxt-themes/docus#757]

**Comment by Tahul** [comment]
Hello :)

Yes sure, you can add: `studio: { enabled: false }` in your nuxt.config.

It should entirely disable the Studio integration.

**Comment by Barbapapazes** [comment]
I think there is a type issue.

![image](https://user-images.githubusercontent.com/45267552/212698266-3585878b-d78a-477b-8aed-40159d64f3ed.png)

**Comment by Atinux** [comment]
Does it create a problem for having the __studio.json since it is not requested by Docus in any way?

**Comment by Tahul** [comment]
@Atinux I would say performances, it makes the generate longer as it parses a lot of metas from the project files.

**Comment by Barbapapazes** [comment]
Yes, exactly the reason!

**Comment by Tahul** [comment]
Even with type error, did the line I sent you fixed your issue?

If so, could you please close this one? thank you 🙏

**Comment by Barbapapazes** [comment]
Nop, `__studio` still here.

**Comment by mao-shonen** [comment]
this working for me

`nuxt.config.ts`
```ts
export default defineNuxtConfig({
nitro: {
    prerender: {
      ignore: ['/__studio.json'],
    }
}
```

**Comment by Barbapapazes** [comment]
> this working for me
> 
> `nuxt.config.ts`
> 
> ```ts
> export default defineNuxtConfig({
> nitro: {
>     prerender: {
>       ignore: ['/__studio.json'],
>     }
> }
> ```

Yep, works fine! Thanks
