### ISSUE TITLE
Wrong grid when aside is `false` 

### ISSUE THREAD

**Issue by Barbapapazes** [nuxt-themes/docus#758]
When `aside` is set to `false`, the layout is broken. This is because, the div is completely removed to content take the first col.

![image](https://user-images.githubusercontent.com/45267552/212651196-7dee9b09-4049-41ba-845a-6cae84ee0a20.png)

![image](https://user-images.githubusercontent.com/45267552/212651222-d8c617ec-4605-499e-b2e4-1ece737d22a6.png)

**Comment by bdrtsky** [comment]
How it suppose to look without aside @Atinux ?

**Comment by Tahul** [comment]
@bdrtsky ; center container taking full width of aside, preserving ToC the same if it's still enabled.

**Comment by bdrtsky** [comment]
why use same layout for this? this is basically full width layout.

**Comment by Atinux** [comment]
Makes sense to have another layout for this
