### ISSUE TITLE
Choose Toc depth

### ISSUE THREAD

**Issue by Barbapapazes** [nuxt-themes/docus#760]
Hello,

Is there a way to change the Toc depth?

Thanks !

**Comment by Tahul** [comment]
Hello :)

You can find the documentation about the ToC here:
https://content.nuxtjs.org/api/configuration#toc

**Comment by Barbapapazes** [comment]
ok, it's the same as Nuxt Content. Nice to know.

**Comment by Barbapapazes** [comment]
Yep, I was aware of this but I was looking at this page https://docus.dev/introduction/configuration and seeing no mention on Nuxt Content config, I didn't think it was possible.
