### ISSUE TITLE
Card Grid decoration doesn't change color

### ISSUE THREAD

**Issue by Barbapapazes** [nuxt-themes/docus#763]
In this component, https://elements.nuxt.space/landing/card-grid#cardgrid, there is a rounded blurred decoration. But using `pinceau` config file, I expected that change the color to have a fully harmonized first page. Unfortunately, that's not the case.

Currently

![image](https://user-images.githubusercontent.com/45267552/213119760-ce042fb6-5fa3-4495-8db5-657d1b709ed7.png)

**Comment by bdrtsky** [comment]
rounded blurred decoration in codegroup? where's it on your screenshot? not really sure I understand what you mean

**Comment by Barbapapazes** [comment]
Yes, I'm speaking about this component. (Screenshot from my local computer but soon on internte)

https://elements.nuxt.space/landing/card-grid

The blurred circle doesn't change colors to use theme colors from `pinceau`.

Here my config:

```ts
import { defineTheme, palette } from 'pinceau'

export default defineTheme({
  color: {
    primary: palette('orange')
  }
})
```

But maybe I need to add more config to this file?

**Comment by Barbapapazes** [comment]
I'm talking about `ellipsis` https://elements.nuxt.space/globals/ellipsis (but there is no exemple so I did not understand that was this.

**Comment by Barbapapazes** [comment]
Ho, I understand, I called `CardGrid`  `CodeGrid`. Sorry about this confusion.

**Comment by bdrtsky** [comment]
I am afraid, right now `Ellipsis` gradient is hardcoded, as Pinceau struggles with `rgba` function, but maybe @Tahul knows the way to make it use generated palette?

**Comment by Tahul** [comment]
Hey :)

@Barbapapazes we can definitely change that inside the Ellipsis for sure.

Also, what you can do is copy the component with the exact same name in your `components/` directory, and replace the implementation with yours, and you should be fine! :)

**Comment by Barbapapazes** [comment]
Thanks for the response. As I can see in elements, it's possible to pass a props and the overwrite is a nice idea.
