### ISSUE TITLE
Wrong style to copy button in light theme

### ISSUE THREAD

**Issue by Barbapapazes** [nuxt-themes/docus#764]
The copy button, used in a code bloc, is not correctly styled in light theme.

In dark theme:
![image](https://user-images.githubusercontent.com/45267552/213131178-cfabdb9d-a08f-4bc8-bebb-aa83d49092d7.png)

But in light theme:
![image](https://user-images.githubusercontent.com/45267552/213131236-7f08fe4a-c970-428c-8202-004337e3068d.png)

**Comment by Atinux** [comment]
Seems related to https://github.com/nuxt-themes/typography/commit/c31d603

cc @Tahul

**Comment by Atinux** [comment]
The bug is present on https://typography.nuxt.space/

Feel free to make a PR on Typography @Barbapapazes

**Comment by Barbapapazes** [comment]
Ok, thanks to know! Will look at it soon.

**Comment by bdrtsky** [comment]
I pushed the fix to Typoraphy

**Comment by Barbapapazes** [comment]
Amazing!

**Comment by Barbapapazes** [comment]
Fixed in https://github.com/nuxt-themes/typography/commit/3ee10130dbfd830749a8d88f760417e456bbc732

**Comment by Atinux** [comment]
Released: https://github.com/nuxt-themes/typography/releases/tag/v0.4.2

**Comment by Barbapapazes** [comment]
That was quick! 🚀
