### ISSUE TITLE
Navbar links are not appearing!

### ISSUE THREAD

**Issue by otabekoff** [nuxt-themes/docus#769]
Navbar menu links are not appearing! My content folder structure looks like 👇
Am I doing anything wrong?

📦content
 ┣ 📂1.guide
 ┃ ┣ 📂1.welcome
 ┃ ┃ ┣ 📜1.index.md
 ┃ ┃ ┣ 📜2.stacks.md
 ┃ ┃ ┣ 📜3.quick-start.md
 ┃ ┃ ┣ 📜4.getting-help.md
 ┃ ┃ ┣ 📜5.faq.md
 ┃ ┃ ┗ 📜_dir.yml
 ┃ ┣ 📂2.components
 ┃ ┃ ┣ 📜1.index.md
 ┃ ┃ ┣ 📜2.nuxt-3.md
 ┃ ┃ ┣ 📜3.typescript.md
 ┃ ┃ ┗ 📜_dir.yml
 ┃ ┣ 📂3.resources
 ┃ ┃ ┣ 📜1.index.md
 ┃ ┃ ┣ 📜2.coding-setup.md
 ┃ ┃ ┣ 📜3.breakpoint-debugging.md
 ┃ ┃ ┣ 📜4.commands.md
 ┃ ┃ ┗ 📜_dir.yml
 ┃ ┣ 📜index.md
 ┃ ┗ 📜_dir.yml
 ┣ 📂2.nuxt-auth
 ┃ ┣ 📂1.getting-started
 ┃ ┃ ┣ 📜1.index.md
 ┃ ┃ ┣ 📜2.installation.md
 ┃ ┃ ┣ 📜3.quick-start.md
 ┃ ┃ ┣ 📜4.getting-help.md
 ┃ ┃ ┗ 📜_dir.yml
 ┃ ┣ 📂2.configuration
 ┃ ┃ ┣ 📜1.index.md
 ┃ ┃ ┣ 📜2.nuxt-config.md
 ┃ ┃ ┣ 📜3.nuxt-auth-handler.md
 ┃ ┃ ┗ 📜_dir.yml
 ┃ ┣ 📜1.index.md
 ┃ ┗ 📜_dir.yml
 ┣ 📂3.nuxt-session
 ┗ 📜0.index.md

**Comment by JesusVazquezDev** [comment]
DISCLAIMER: I just started working with this repo so I'm not 100% sure this is the solution for you. 
If I understand your question, you'd like the navigation bar to appear at the top of the page? 

If that is the case, you should increment the aside.level from 0 to 1 in app.config.ts.

Let me know if this helps!

**Comment by otabekoff** [comment]
If I understood you correctly, you're saying that ``aside.level 1`` means `true` and `0` is for `false`? I think they should work on the docs more yet. If I could, I would be helping to do that.

**Comment by JesusVazquezDev** [comment]
Awesome, glad it worked! 

If you wanted to know a bit about the logic on the backend of things(for the navigation bar), I figured this solution out by looking at the AppHeaderNavigation.vue file located in node_modules/nuxt-themes/docus/components/app. 

On line 7, you can see that as long as aside.level != 0 it should show the navbar ( though this is my interpretation, I'm fairly new to Vue as a whole ). 

But yeah I agree, I'd be open on working on the docs as well.

**Comment by otabekoff** [comment]
Thanks! I also look for the node_modules/nuxt-theme/docus for more. I am closing as of it is worked for now.
