### ISSUE TITLE
Navbar logos are not working.

### ISSUE THREAD

**Issue by otabekoff** [nuxt-themes/docus#772]
Docus is not getting `logo-dark.svg` and `logo-light.svg` files as logo for dark and light modes. I've replaced them with my own SVG logos. But it is not working.

My **header** settings of `app.config.ts` file are like below:
```js
    header: {
      logo: true,
      showLinkIcon: true,
      exclude: []
    },
```

**Comment by otabekoff** [comment]
I looked for the ``node_modules`` folder and found ``AppHeaderLogo.vue`` component in ``@nuxt-themes/docus/components/app`` directory. Then I found this:
![image](https://user-images.githubusercontent.com/60849894/213863645-f32287f7-e1ab-4ecb-a174-7f232a75c66a.png)

In the above image, it is told that ``logo`` constant value is what the value the user set in ``docus.value.header?.logo``. Does it equal to docus.header.logo of ``app.config.ts``?

Ok, the next, in the NuxtLink, component tag of Vue is used.

But below it is told to use Logo.vue component with v-else-if. It is only the docus logo. Else, the title is being used with v-else-if.

Let's now look at the v-if. It is written to the ``<component>``.

It is ``<component :is="logo" v-if="logo && typeof logo === 'string'" />``.

What means the ``:is="logo"`` if we set `logo: true` in `app.config.ts`, them it is equal to `is="true"`.

Also, let's look at the v-if. Let's say we set `logo: "/logo.svg"` in `app.config.ts`. Then, v-if logic will be like this: ``"/logo.svg" && true``.

So, as a final result we will have 3 options:
- Logo + Title
- Logo only
- Title only

This looks normal. But what about light mode logo and dark mode logo? Why doesn't below sytnax is not supported?

```js
logo: {
    light: ""
    dark: ""
}
```

After you do some changes and make final edit. Please add more info about this in docus.dev website, please.

**Comment by otabekoff** [comment]
If you are goint to say "You should create a Logo.vue component and then use it. After that <component> tag's ``is`` renders your Vue component as logo",  why ``header.logo`` is not accepting string? Please, fix that.

**Comment by YesidMarin** [comment]
Any update?

**Comment by bdrtsky** [comment]
@YesidMarin you can check this PR if you want https://github.com/nuxt-themes/docus/pull/874
Should be merged in few days.

**Comment by YesidMarin** [comment]
@bdrtsky thank you! I will be waiting for updates!"
