### ISSUE TITLE
Questions about Docus icon libraries?

### ISSUE THREAD

**Issue by otabekoff** [nuxt-themes/docus#773]
### Ask your question

I know that Docus uses some kind of Icon library. One that I know is Hero Icons.

Questions:
- Which version of HeroIcons does Docus use?
- If Docus uses HeroIcons 1.0.6, How we can upgrade it or Can you upgrade it to the latest version?
- What other Icon libraries does Docus use?
- I want some Docus icon but they are not working. Why?
- How we can use other icon libraries?
- Will you add more about icons into the docs of Docus?
- Can you give more detailed answer please?

### What's happening exactly?
icon: heroicons-outline:rocket is not working in _dir.yml

### Additional information

https://heroicons.com/

**Comment by bdrtsky** [comment]
Hey. Docus is using [`NuxtIcon`](https://github.com/nuxt-modules/icon) component, which is using [Iconify](https://iconify.design/)
