### ISSUE TITLE
Writing multiline text in & changing the height of code-terminal.

### ISSUE THREAD

**Issue by otabekoff** [nuxt-themes/docus#776]
Now, Code Terminal component has set fixed value, in my opinion. We can see it in the image which is a screenshot from a smartphone.
![image](https://user-images.githubusercontent.com/60849894/213883272-a86899f2-de22-4da4-80b2-d6aad50a31c0.png)

It has more free space. We should get rid of it. Do we need something additional like `turnOffFixedValue`?

Also is it possible to write multiline code in this terminal component or not? If no, please implement it.

**Comment by otabekoff** [comment]
@bdrtsky Any updates? In theses days, On what the tams is working? If it is not a secret, can you tell?

**Comment by bdrtsky** [comment]
@otabekoff sorry for late answer. Next week `Elements` should open public, and `Terminal` is tokenized, so you can set height yourself. 

As for multiline code, it's already possible. Just pass an array of strings instead

**Comment by otabekoff** [comment]
Also, I will use it in my project. I am closing this as it is live and working at docus.dev as an instance.
