### ISSUE TITLE
Is there a way to change color NuxtLoadingIndicator?

### ISSUE THREAD

**Issue by Barbapapazes** [nuxt-themes/docus#779]

**Comment by Atinux** [comment]
I guess we could create tokens for it and use them on https://github.com/nuxt-themes/docus/blob/acac5c3466b329cb327ed2d2a216b2cc53448179/components/app/AppLoadingBar.vue#L105

WDYT @Tahul ?

**Comment by bdrtsky** [comment]
Sure, will do
