### ISSUE TITLE
The last navigation button clickable area shrinks

### ISSUE THREAD

**Issue by jsonleex** [nuxt-themes/docus#781]
The clickable area of the last navigation button is covered by other elements 👇

<img width="1202" alt="iShot_2023-01-25_08 50 10" src="https://user-images.githubusercontent.com/25883665/214455031-3c4d4e2a-a8fc-417c-822a-f8eae64b3f98.png">

Related to the following code

https://github.com/nuxt-themes/docus/blob/acac5c3466b329cb327ed2d2a216b2cc53448179/components/app/AppHeader.vue#L82-L92

[Layering items with z-index - MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Grid_Layout/Basic_Concepts_of_Grid_Layout#layering_items_with_z-index)

Add `z-index: 1` to `header .section.center` resolves this Bug

**Comment by bdrtsky** [comment]
Resolved here https://github.com/nuxt-themes/docus/pull/870
