### ISSUE TITLE
Cannot render global components with MDC

### ISSUE THREAD

**Issue by creativebymonarch** [nuxt-themes/docus#815]
Hi,

I'm working on a component package, and I want to display my own components with "preview" and "code" tab.
The components that I want to display are on NPM. It's works when it is on a ".vue" page, but not on .md.

I've tried to display global components as it explained on the Nuxt Content documentation, but it doesn't work.

Here is the error :

`[Vue warn]: Failed to resolve component: TwLoading
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement. `

and here is my code : 

```
::code-group
   ::code-block{label="Preview" preview}
    ::TwLoading
   ::
   ::code-block{label="Code"}
    ...
   ::
::
```

Is it possible to do it now or not yet ?

Thanks !

**Comment by Tahul** [comment]
Hey; I think you are using your `TwLoading` component wrong in MDC.

You seem to have forgot the closing tag!

```ts
::code-group
   ::code-block{label="Preview" preview}
    ::TwLoading
    ::
   ::
   ::code-block{label="Code"}
    ...
   ::
::
```

Could you try that out and reach out if it solves your issue?

**Comment by creativebymonarch** [comment]
Thanks for reply !

But it does the same error..

```javascript
[Vue warn]: Failed to resolve component: TwLoading
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement. 
  at <CodeGroup > 
  at <AsyncComponentWrapper > 
  at <ContentRendererMarkdown value= {_path: '/components/loading', _dir: 'components', _draft: false, _partial: false, _locale: '', …} excerpt=false tag="div" > 
  at <ContentRenderer key="content:2.components:3.loading.md" value= {_path: '/components/loading', _dir: 'components', _draft: false, _partial: false, _locale: '', …} > 
  at <Container fluid=true padded=undefined class="docs-page-content fluid" > 
  at <DocsPageLayout> 
  at <Default > 
  at <LayoutLoader key="default" name="default" hasTransition=false > 
  at <FragmentWrapper > 
  at <NuxtLayout name="default" > 
  at <DocumentDriven onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< undefined > > 
  at <RouteProvider key="/components,loading" routeProps= {Component: {…}, route: {…}} pageKey="/components,loading"  ... > 
  at <FragmentWrapper > 
  at <RouterView name=undefined route=undefined > 
  at <NuxtPage> 
  at <AppLayout> 
  at <App key=2 > 
  at <NuxtRoot>
```

If I create a `TwLoading.vue` component in `./components/content` folder, it works perfectly ! But not in global with package

Is it possible in configuration file to add components folders to explore ?

**Comment by Tahul** [comment]
```
defineNuxtConfig({
   components: [{ path: './path', global: true  }]
})
```

This should be enough!

I'm closing this for now, but feel free to re-open if you still have this bug!
