### ISSUE TITLE
Dynamic _slug.vue in pages folder 

### ISSUE THREAD

**Issue by PGimenez** [nuxt-themes/docus#816]
I want to display every article that has been tagged with a specific string. For this, I've created a dynamic page `pages/tags/_slug.vue`, where I read the `tags`attribute in the frontmatter of every document in /content. However, when I access `tags/<tagname>` I'm getting a 404 not found error.

From [what I've read](https://github.com/nuxt/content/issues/1656), this is because of the `DocumentDriven` mode. I see it is possibe to [disable this mode](https://content.nuxtjs.org/guide/writing/document-driven/#disable-or-control-the-page-data) on a per-page basis, but I don't know how to disable it for the `tags/`route.  

Is there any way to make my tags work?

**Comment by hartmut-co-uk** [comment]
With nuxt3 the file naming pattern has [changed](https://nuxt.com/docs/migration/pages-and-layouts#pages).

=> Is it working with `pages/tags/[slug].vue` by any chance?

**Comment by PGimenez** [comment]
It worked, thanks! Now I can get the route parameters in the page with

```vue
<script setup>
      const route = useRoute()
      const slug = route.params.slug // When calling /abc the slug will be "abc"
</script>

<template>
  <h1>{{ slug }}</h1>
</template>
```
