### ISSUE TITLE
Build halts when generating content for `/api` folder

### ISSUE THREAD

**Issue by RocKing1001** [nuxt-themes/docus#826]
**Docus version**: 1.8.2 (happens with 1.8.1 as well, did not test any other)
**Problem**: Building the project halts when reaching
```
[info] [nitro] Prerendering 4 routes
--
[log] [nitro]   ├─ /api/_content/cache.1676915610823.json (1365ms)
```

**Steps to reproduce**: clone [github.com/Tectone23/docs.tcore.io](https://github.com/Tectone23/docs.tcore.io )  (or start with a starter docus project) and then run `yarn build` (or build using npm or pnpm, I tested them all)

**Expected behaviour**: The project builds and generates a proper output.

**Comment by RocKing1001** [comment]
I found a temporary solution to this. I copied the lockfile from this repo (pnpm-lock.yaml) and used it in my site. It is a tape-on solution, but I needed to fix this issue immediately due to deadlines.

**Comment by just-maik** [comment]
I guess this is the same Issue as #827

**Comment by Tahul** [comment]
@RocKing1001 ; could you link me the lockfile that works for you?

**Comment by Tahul** [comment]
That would help on knowing which update broke your site.

**Comment by RocKing1001** [comment]
> @RocKing1001 ; could you link me the lockfile that works for you?

https://github.com/Tectone23/docs.tcore.io/blob/main/pnpm-lock.yaml this is the one which works

**Comment by Tahul** [comment]
@RocKing1001 ; so this one works and upgrading to latest versions breaks?

**Comment by just-maik** [comment]
I tried using the pnpm-lock but couldn't get it to work.

**Comment by oripka** [comment]
Not sure this is a docus problem. With the linked [yarn.lock](https://gist.github.com/oripka/273a5930487b12c144693db0be9d4785) (on nuxt 3.2.0) it works fine for me with the following output

```
ℹ Prerendering 4 routes                                                                                                        nitro 17:29:46
  ├─ /api/_content/cache.1676996954676.json (3728ms)                                                                           nitro 17:29:50
  ├─ /__studio.json (1304ms)                                                                                                   nitro 17:29:53
ℹ Building Nitro Server (preset: node-server)
```

After running `yarn upgrade nuxt@3.2.1` the `npx nuxi build` hangs at 

```
ℹ Initializing prerenderer                                                                                                     nitro 17:34:07
ℹ Prerendering 4 routes                                                                                                        nitro 17:34:13
  ├─ /api/_content/cache.1676997220038.json (3465ms)                                                                           nitro 17:34:17
```

**Comment by just-maik** [comment]
Can't reproduce the Issue in the StackBlitz anymore. I think the nitro@2.2.3 that released yesterday fixed it.

**Comment by just-maik** [comment]
@RocKing1001 when deleting the pnpm-lock and reinstalling nuxt@3.2.2 that now uses nitro@2.2.3 [your repo](https://github.com/Tectone23/docs.tcore.io) did build without Issues.

**Comment by RocKing1001** [comment]
> @RocKing1001 when deleting the pnpm-lock and reinstalling nuxt@3.2.2 that now uses nitro@2.2.3 [your repo](https://github.com/Tectone23/docs.tcore.io) did build without Issues. 

The current branch of my repo has the lockfile copied from the docus main repo. The `yarn-old` branch is the one with the issues. It uses yarn and has a yarn.lock file.

**Comment by RocKing1001** [comment]
> Can't reproduce the Issue in the StackBlitz anymore. I think the nitro@2.2.3 that released yesterday fixed it.

I will try it out to see if it fixed it.

**Comment by RocKing1001** [comment]
> Can't reproduce the Issue in the StackBlitz anymore. I think the nitro@2.2.3 that released yesterday fixed it.

Yes, it seems to be fixed now, I cant reproduce the issue either.

**Comment by just-maik** [comment]
So TLDR for everyone running into this:
Update to nuxt 3.2.2 using nitro 2.2.3.

**Comment by oripka** [comment]
yes it's fixed for me, too
