### ISSUE TITLE
Permenant Redirects

### ISSUE THREAD

**Issue by zoey-kaiser** [nuxt-themes/docus#829]
Hello Docus Team!

I was wondering if it is possible to have a custom redirect file in which you could assign multiple permanent redirects. 
We are currently migrating some older links to new locations and we want the old links to redirect to the new ones. 

I would like to avoid having to create files in all the old locations with a redirect in the old file headers as that would really mess up the pretty file structure. 

Is there a solution for this/ What would you recommend?

**Comment by Atinux** [comment]
Depending of the hosting provider, you can directly create a `vercel.json` or `public/_redirects.yml` (Netlify) to do so.

Since docus docs are mostly SSG, it is tricky to support those redirects properly for SEO (doing client-side redirects is not best)
