### ISSUE TITLE
[Components] No TOC so wide content?

### ISSUE THREAD

**Issue by Barbapapazes** [nuxt-themes/docus#833]
Hello,

When there is no TOC, content is wider

![image](https://user-images.githubusercontent.com/45267552/221811745-145ba0f0-4703-4368-8484-7ada95ca2a4b.png)

I think it's an issue because TOC are not disabled. On another page, here the result:

![image](https://user-images.githubusercontent.com/45267552/221811903-67ef0ea0-e842-4146-8a5b-afc83d49842a.png)

**Comment by Atinux** [comment]
We are thinking of keeping the right aside and add more content into it, not only toc.

This might be a breaking change though

**Comment by Tahul** [comment]
Hey; closing this in favor of #877 ; feel free to continue the discussion there!
