### ISSUE TITLE
Aside is not showed up when only have 1 navigation

### ISSUE THREAD

**Issue by gravitano** [nuxt-themes/docus#836]
Hi,

I have content with the following structure.

<img width="252" alt="image" src="https://user-images.githubusercontent.com/5087538/222073998-7d2ba2f2-bea0-4de0-8dd9-66b9af9c6399.png">

Previously, the aside menu was there. But, when I upgrade to the latest version, the aside is gone.

I think it is because of this change https://github.com/nuxt-themes/docus/commit/ed3dd92b1d95e51ddb3551db0e3058a341893d9e.

**Comment by Atinux** [comment]
Actually the `navigation.value.length` should be of two, do you have a reproduction I can check?

**Comment by gravitano** [comment]
Sure. Here's the repro: [Stackblitz](https://stackblitz.com/~/github.com/gravitano/docus-reproduction) - [Repo](https://github.com/gravitano/docus-reproduction)

**Comment by Atinux** [comment]
Could you try [v1.9.2](https://github.com/nuxt-themes/docus/releases/tag/v1.9.2) @gravitano ?

**Comment by Atinux** [comment]
Actually v1.9.3 so I fixed the mobile navigation too for your example.

**Comment by Atinux** [comment]
v1.9.4 should work perfectly whatever your `aside.level` also!

**Comment by gravitano** [comment]
It's working perfectly now. Thank You!
