### ISSUE TITLE
Rendering CodeGroup in custom component - missing tabs

### ISSUE THREAD

**Issue by kduma** [nuxt-themes/docus#848]
Hello,

I have created created custom component with following template:

```vue
<template>
  <CodeGroup>
    <CodeBlock label="Tab 1">
      Tab 1
    </CodeBlock>
    <CodeBlock label="Tab 2">
      Tab 2
    </CodeBlock>
  </CodeGroup>
</template>

<script>
export default {
  name: "Custom"
}
</script>

<style scoped>
</style>
```

In content page I call it using MDC syntax (`:custom`), but in the result it only shows first tab without any tabs.

What is missing here to use `CodeGroup` in my component?

BTW, where can I find the source code for `CodeGroup`? Theoretically it is in `@nuxt-themes/elements` package, but there is no repo for it. 😄

**Comment by Atinux** [comment]
Hi @kduma 

It's always best to provide a reproduction so we can help as fast as possible.

The repo is not open source yet but you can find the source on https://www.npmjs.com/package/@nuxt-themes/elements?activeTab=explore

**Comment by kduma** [comment]
Hi @Atinux,

I have prepared repository here: [github.com/kduma/docus-test](https://github.com/kduma/docus-test) - and a preview here: [kduma.github.io/docus-test/](https://kduma.github.io/docus-test/).

Here are: 
- sample component: [components/content/Test.vue](https://github.com/kduma/docus-test/blob/main/components/content/Test.vue)
- and page where it is used: [content/0.index.md](https://github.com/kduma/docus-test/blob/main/content/0.index.md?plain=1)

**Comment by Atinux** [comment]
I released a new version of Elements to fix your issue, you can upgrade your dependencies  (`npm update`)

Demo: https://stackblitz.com/edit/github-rovjib?file=components%2Fcontent%2FTest.vue
