### ISSUE TITLE
Allow modifying rel in footer

### ISSUE THREAD

**Issue by Barbapapazes** [nuxt-themes/docus#862]
Hello,

Is-it possible to modify rel in the footer text links?

https://github.com/nuxt-themes/docus/blob/main/components/app/AppFooter.vue#L23

In want to change rel using a key in the config.

```ts
  {
        text: "ArmoniK",
        target: "_blank",
        href: "https://aneoconsulting.github.io/ArmoniK/",
        rel: "" // This will set no rel
      },
```

And in the AppFooter.vue

```html
<NuxtLink
  :rel="link.rel"
>
...
```

Here a exemple if user does not provide a rel or when the rel is empty
https://stackblitz.com/edit/nuxt-starter-5z8mvo?file=app.vue

**Comment by Atinux** [comment]
It could be possible, happy to open a PR?
