### ISSUE TITLE
Bug: cannot render last page

### ISSUE THREAD

**Issue by liyasthomas** [nuxt-themes/docus#873]
Updated deps to the latest and a new error is happening.

Last page irrespective of its content is not rendering - `<DocsPrevNext/>` component is causing the error.

Here's a screenshot of the error in local dev environment. Production build (`nuxi generate`) completes but the last page's route is giving 404.

<img width="1470" alt="Screenshot 2023-03-29 at 1 52 03 PM" src="https://user-images.githubusercontent.com/10395817/228472301-8237fb10-9d21-4256-ab1a-61699e830f06.png">

Dependencies
```
"@nuxt-themes/docus": "^1.10.1",
"nuxt": "^3.3.2"
```

**Comment by bdrtsky** [comment]
I can't reproduce this. @Tahul mind take a look?

**Comment by Atinux** [comment]
Could you please share a reproduction?

**Comment by bdrtsky** [comment]
This might fix your issue https://github.com/nuxt-themes/docus/pull/879 @liyasthomas Mind checking it?

**Comment by liyasthomas** [comment]
Can confirm #879 fixed the issue. Looking forward to the patch release soon.
<sub>Kindly close this issue once released.</sub>

**Comment by mcdaded** [comment]
Hit this issue as well, any idea when will the patch release be out?

**Comment by liyasthomas** [comment]
[v1.11.0](https://github.com/nuxt-themes/docus/releases/tag/v1.11.0) fixed this issue, hence closing.
