### ISSUE TITLE
Should DocsPrevNext.vue display directories title ?

### ISSUE THREAD

**Issue by mathieunicolas** [nuxt-themes/docus#883]
Hello there,

See the DocsPrevNext.vue component at the bottom of this page : https://docus.dev/introduction/configuration
The `api` directory is displayed as `Api` but its title is set and rendered in the AsideTree.vue as `API`.

Maybe it would be interesting to harmonize this display, by displaying in this example `API` as well ?
What do you guys think about this ?

**Comment by bdrtsky** [comment]
Related https://github.com/nuxt-themes/docus/issues/821

I think this might be a Nuxt Content issue...

**Comment by mathieunicolas** [comment]
Thanks a lot @bdrtsky !
Cheers from France !
