### ISSUE TITLE
How to set a favicon?

### ISSUE THREAD

**Issue by moisout** [nuxt-themes/docus#884]
There is no documented way to set a favicon, other than to just have a favicon.ico file in the public folder, and trust the browser to read /favicon.ico.

**Comment by Barbapapazes** [comment]
Maybe moisout want use a URL (like for og:image).

**Comment by jgngo** [comment]
You can use setup this in `nuxt.config.ts`. The href path to your favicon will be relative to `/public` folder.

```
export default defineNuxtConfig({
  extends: '@nuxt-themes/docus',
  app: {
    head: {
      title: 'YOUR TITLE',
      link: [
        { rel: 'icon', type: 'image/x-icon', href: '/favicon.png' }
      ]
    }
  }
})
```
