### ISSUE TITLE
A new callout?

### ISSUE THREAD

**Issue by Barbapapazes** [nuxt-themes/docus#887]
Hello,

You say on the elements website that callout are subject to change. Have you an idea for a landing date?

https://elements.nuxt.space/globals/callout#callout

**Comment by Atinux** [comment]
cc @bdrtsky

**Comment by bdrtsky** [comment]
@Barbapapazes big update for Docus (including updated and finally published Elements and Tokens) planned by the end of the month, stay tuned 👋

Regarding the question, Elements will have updated Alert, Callout and Disclosure component.

**Comment by Barbapapazes** [comment]
> @Barbapapazes big update for Docus (including updated and finally published Elements and Tokens) planned by the end of the month, stay tuned 👋
> 
> Regarding the question, Elements will have updated Alert, Callout and Disclosure component.

Okk that so nice! Will stay tuned!

**Comment by iqlal** [comment]
@bdrtsky wowwww 🎇

**Comment by Tahul** [comment]
Related to #909 :)
