### ISSUE TITLE
[Components] Sticky Navigation and TOC

### ISSUE THREAD

**Issue by derHodrig** [nuxt-themes/docus#897]
I suggest the optional setting of having sticky navigation and table of contents.

In large pages, it is not really user-friendly, if the user wants to switch to other page, the user needs to scroll right to the top. As an example, I would say [Something like the Vuetify Docs](https://vuetifyjs.com/en/getting-started/installation/) do it in a useful way. Maybe sticky is the wrong term, since the navigation and TOC are separated from the middle content section.

What do you think?

**Comment by bdrtsky** [comment]
It's should be sticky by default. Could you share link/repro so I could take a look?

**Comment by derHodrig** [comment]
You are right!
The issue is with vuetify. We use vuetify to implement some extra components. So the way how to fix it, would be to create a layout for the docs pages, put the header, left menu, right menu and content (vuetify way) in it and setup a dir yml to let the docs pages know "use the docs layout" right?

https://stackblitz.com/edit/github-tlattr?file=nuxt.config.ts

**Comment by derHodrig** [comment]
> @derHodrig checked your link. You could try to overwrite this `body` CSS `overflow-y: scroll;` with `overflow-y: visible`. Seems like it fixes it?

Gorgeous! Thanks, that's it, thank you for that trick! Closing this, since its solved.
