### ISSUE TITLE
Can't use components installed via a nuxt Module. 

### ISSUE THREAD

**Issue by cory-glooh** [nuxt-themes/docus#907]
Trying to use Docus, to build documentation for my component library. but when I add it as a module in the nuxt config, and try and render it in a markdown page, i get `[Vue warn]: Failed to resolve component, If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement`. But it works fine when using it in other nuxt applications.

**Comment by Tahul** [comment]
Hello; to get your components working inside your content, you need to mark them as `global: true` in your `nuxt.config`.

You can take a look around here to get more infos about this:
https://content.nuxtjs.org/guide/migration/from-v1#global-components
