### ISSUE TITLE
incompatible node v20.x.x

### ISSUE THREAD

**Issue by adityadees** [nuxt-themes/docus#922]
Request compatible with latest node version

<img width="1146" alt="image" src="https://github.com/nuxt-themes/docus/assets/37553901/30da0dbe-ba2b-4d0f-8306-b7d5f6069bba">

**Comment by Atinux** [comment]
Related directly to nuxt/kit here, I guess @danielroe knows the reason about node 20

**Comment by adityadees** [comment]
ah okay so still need some configuration right?
I thought I can just do this and all will done xD
```
npx nuxi@latest init -t themes/docus
cd docs
npm install
npm run dev
```

**Comment by Atinux** [comment]
Try to run `npx nuxi upgrade` in your project @adityadees

**Comment by adityadees** [comment]
alright it's ok thanks, let's try it later
I've used another docs themes
