### ISSUE TITLE
[Bug] Incorrect Text Highlighting in Internal Search for Cyrillic Characters

### ISSUE THREAD

**Issue by XenBG** [nuxt-themes/docus#942]
When conducting an internal search using Cyrillic characters, the highlighting feature erroneously highlights characters that do not correspond to the search query.

The searched term is "клиентската зона" (the Client Area), later changed to "клиентска зона" (a Client Area).

Demo:

https://github.com/nuxt-themes/docus/assets/4932709/a3660b8a-1a46-4e4a-9910-8bebc0d77264

**Comment by Atinux** [comment]
Would love to get your input @bdrtsky

**Comment by bdrtsky** [comment]
I've exposed Fuse.js config, you can now set it yourself @XenBG 

The default is

```
{
      fuseOptions: {
        keys: [
          'title',
          'description',
          'keywords',
          'body'
        ],
        ignoreLocation: true,
        threshold: 0,
        includeMatches: true,
        includeScore: true,
      },
      matchAllWhenSearchEmpty: true
    }
```

Could you please check Fuse options and see if it helps fix Cyrillic issues? https://www.fusejs.io/api/options.html

**Comment by XenBG** [comment]
By adjusting the `threshold` value in Fuse.js's options, I can obtain different results for the same submitted keywords. As far as I understand, the highlighted text around the keywords is a desired effect in Fuse.js's functionality, although it may not be perfect. Nevertheless, having control over some of the settings allows for a more customized experience. With these changes, the issue can be considered resolved, and I appreciate your clarification on this matter!
