### ISSUE TITLE
Protected Routes

### ISSUE THREAD

**Issue by JK-Effects** [nuxt-themes/docus#946]
Can some routes be protected with middleware to prevent access for some users?

For example, that you show a selfbuild login form by default if the user is not authenticated. 
Otherwise a middleware would redirect the user to see the restricted pages.

**Comment by 1bye** [comment]
Try go into `node_modules/@nuxt-themes/docus/` and there add `middleware` folder, with middlewares.

(I'm not tried this)

**Comment by JK-Effects** [comment]
In the middleware docus (node_modules) folder it would work.
But using it in the projectfolder itself, I now tried it directly with a global middleware:
  
auth.global.js in the projects middleware folder
```
export default defineNuxtRouteMiddleware((to, from) => {
  console.log(to, from);
  var loggedin /*some validation function*/
  if (!loggedin) {
    return navigateTo("/login");
  }
});
```

I was not sure if it would work at all with this template / nuxt-content package.

**Comment by haifahrul** [comment]
I have tried using auth.global.js, but the result is that I can't get the store that I have defined, can you give me a solution?

Thanks
