### ISSUE TITLE
Deployment Error

### ISSUE THREAD

**Issue by JK-Effects** [nuxt-themes/docus#949]
Deploying the App delivers an error called `this.docs.forEach is not a function`.
By downgrading the nuxt version I got more debugging messages and I dicovered this is due to the AppSearch element in the navbar.

Removing the AppSearch Component in the `\node_modules\@nuxt-themes\docus\components\app\AppHeader.vue` solves this error.
```
...
<div class="section right">
 <!-- <AppSearch />  <- remove this part-->
  <ThemeSelect />
  <div class="social-icons">
    <AppSocialIcons />
  </div>
</div>
...
```
I don't know why this component is broken. In dev-mode it works totally fine.

Quick fix: Optionally, the component can also be copied to the components directory on the project root using the same name.
If the components directory is global, the AppHeader will be overwritten. 
Note that you must remove the AppSearch from the newly created component.

![image](https://github.com/nuxt-themes/docus/assets/79076586/eab66431-0aa9-4724-9e38-a56a7996ff27)

**Comment by Atinux** [comment]
Mind looking at it @bdrtsky ?

**Comment by squpshift** [comment]
+1

**Comment by aburii** [comment]
+1

**Comment by bdrtsky** [comment]
How you deploying it? Local build seems to work.

**Comment by JK-Effects** [comment]
package.json
```json
"devDependencies": {
    "@nuxt-themes/docus": "^1.13.1",
    "@nuxt/devtools": "^0.6.7",
    "@nuxt/eslint-config": "^0.1.1",
    "@nuxtjs/plausible": "^0.2.1",
    "@types/node": "^20.4.0",
    "eslint": "^8.44.0",
    "nuxt": "^3.6.2"
  },
```

Just depoly it with `npm run build` (nuxi build)
