### ISSUE TITLE
nuxt generate: does not create all pages from content folder

### ISSUE THREAD

**Issue by mschoeffmann** [nuxt-themes/docus#959]
using `ssr: true` and `nuxt generate` to generate full static pages does not render pages which were not directly linked from one of the pages or menus.

a workaround would be adding all routes manually to `nitro.prerender.routes`, but shouldn't this be done automatically?

#### reproduction:

https://stackblitz.com/edit/docus-generate-test-ehp6nm-x9fexh?file=README.md

- clone this repository to your local drive
- `pnpm install`
- `pnpm run generate`

check `dist` folder: no `test` pages were generated:

```
  ├─ /404.html (50ms)
  ├─ /200.html (55ms)
  ├─ /api/_content/cache.1690133679277.json (87ms)
  ├─ / (2979ms)
  ├─ /_payload.json (1ms)
  ├─ /api/_content/query/xWeY3NfYtX.1690133679277.json (2ms)
  ├─ /api/_content/navigation/u7BbTyuhiE.1690133679277.json (6ms)
  ├─ /api/_content/query/brX4CwCJoQ.1690133679277.json (14ms)
  ├─ /__studio.json (2999ms)
```

**Comment by Atinux** [comment]
Indeed we do not support generating all pages directly, it might be possible by adding a PR to nuxt/content when the documentDriven mode is enable I guess, happy to open an issue there?
