### ISSUE TITLE
How to change the icon?

### ISSUE THREAD

**Issue by AsynchronousAI** [nuxt-themes/docus#968]
The current icon is
<img width="209" alt="Screenshot 2023-08-20 at 11 11 23 AM" src="https://github.com/nuxt-themes/docus/assets/72946059/97f30803-107c-429b-ad35-f6e879958c57">
I want to switch it to a custom one, how could I do this?

**Comment by Atinux** [comment]
By using the `app.config.ts` file like mentioned on https://docus.dev/introduction/configuration
![CleanShot 2023-08-21 at 10.54.52@2x.png](https://volta.s3.fr-par.scw.cloud/Clean_Shot_2023_08_21_at_10_54_52_2x_675984a5bb.png)

**Comment by AsynchronousAI** [comment]
Thank you!
