### ISSUE TITLE
This project can't be started in Dev mode

### ISSUE THREAD

**Issue by Barbapapazes** [nuxt-themes/docus#978]
Hello,

I would love to contribute to this project but it's impossible to start it.

see https://github.com/nuxt/nuxt/issues/23257

**Comment by Atinux** [comment]
Have you try to upgrade the dependencies @Barbapapazes ?

**Comment by Barbapapazes** [comment]
> Have you try to upgrade the dependencies @Barbapapazes ?

Yes and still the same issue, even on codespaces

**Comment by Atinux** [comment]
Can you try again @Barbapapazes ?

**Comment by Barbapapazes** [comment]
> Can you try again @Barbapapazes ?

Yes, will try it!

**Comment by Barbapapazes** [comment]
From a fresh install from main, I've got this issue 

![image](https://github.com/nuxt-themes/docus/assets/45267552/02e4fc3f-ea49-46a1-9bb9-498e597e479f)

**Comment by Barbapapazes** [comment]
I'm still not able to start it, on codespaces and locally. The node process use 100% of one of my core all the time.

**Comment by Barbapapazes** [comment]
Build works fine.
